name: Calling reusable workflow
on:
  workflow_dispatch:
jobs:
  calling-reusable-wf:
    uses: ./.github/workflows/reusable.yaml
  using-reusable-output:
    needs: calling-reusable-wf
    runs-on: ubuntu-latest
    steps:
      - name: Checking date
        run: echo ${{ needs.calling-reusable-wf.outputs.date }}
  
