name: Calling reusable workflow
on:
  workflow_dispatch:
jobs:
  calling-reusable-wf:
    steps: 
      - name: Calling workflow
        uses: ./.github/workflows/reusable.yaml
  using-reusable-output:
    needs: calling-reusable-wf
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.calling-reusable-wf.outputs.date }}
  
