name: Concurrency
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment
        default: dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 30  
        run: sleep 30
