name: Reusable workflow
on:
  workflow_call:
    outputs:
      date: 
        description: "Date value"
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date-step.outputs.date }}
    steps:
      - name: Echo date
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
        id: date-step

